# Generated by Django 3.1.1 on 2020-10-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/images/banner/placeholder.png', null=True, upload_to='images'),
        ),
    ]
