# Generated by Django 3.1.1 on 2020-10-11 00:10

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201010_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='headline',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripccion'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='info', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Categorias'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=False)),
                ('novedad', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Novedades')),
                ('Tag', models.ManyToManyField(blank=True, null=True, to='app.Tag')),
            ],
        ),
    ]
