# Generated by Django 3.1.1 on 2020-10-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201014_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='canton',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credito',
            name='ciudadela',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='credito',
            name='comunidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='credito',
            name='parroquia',
            field=models.CharField(max_length=100),
        ),
    ]
