# Generated by Django 3.1.1 on 2020-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201014_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='deudor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credito',
            name='garante',
            field=models.BooleanField(default=False),
        ),
    ]
