# Generated by Django 3.1.1 on 2020-10-14 19:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Servicios')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, default='banco.png', null=True, upload_to='productos', verbose_name='Imagen')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='Activar')),
            ],
        ),
    ]
