# Generated by Django 3.1.1 on 2020-10-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Testimonio')),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='testimonios', verbose_name='Imagen')),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='Activar')),
            ],
        ),
    ]
