# Generated by Django 3.1.1 on 2020-10-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_testimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='nav-producto', verbose_name='Imagen')),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='Activar')),
            ],
        ),
    ]
