# Generated by Django 3.1.1 on 2020-10-15 22:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_navproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='navproducto',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
