# Generated by Django 3.1.1 on 2020-10-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_noticiainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='deudor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='garante',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
