# Generated by Django 3.1.1 on 2020-10-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201017_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='deudor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='garante',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
