# Generated by Django 3.1.1 on 2020-11-20 16:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201017_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, default='placeholder.png', null=True, upload_to='nav-servicio', verbose_name='Imagen')),
                ('date', models.DateField(auto_now_add=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('active', models.BooleanField(default=False, verbose_name='Activar')),
            ],
        ),
    ]
